[[build.buildpacks]]
uri = "heroku/nodejs"

[[build.buildpacks]]
uri = "heroku/nodejs-yarn"

[[build.buildpacks]]
uri = "heroku/nodejs-engine"

[[build.buildpacks]]
uri = "heroku/nodejs-npm"

[buildpacks]
uri = "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest"