[[build.buildpacks]]
uri = "heroku/nodejs"

[[build.buildpacks]]
uri = "heroku/nodejs-yarn"

[[build.buildpacks]]
uri = "heroku/nodejs-engine"

[[build.buildpacks]]
uri = "heroku/nodejs-npm"

[project]
id = "io.buildpacks.ffmpeg-script"
name = "ffmpeg Script"
version = "1.0.0"

[build]
exclude = [
    "ffmpeg"
]
include = []

[[build.buildpacks]]
uri = "ffmpeg/"